service: telegram-bots

provider:
  name: aws
  runtime: nodejs10.x
  region: sa-east-1
  memorySize: 256

functions:
  dailyReminder:
    handler: handler.dailyReminder
    events:
      - schedule: cron(0 17 ? * MON-FRI *)

package:
  exclude:
    - .git/**
    - .gitignore
    - .DS_Store
    - npm-debug.log
    - .serverless/**
    - .serverless_plugins/**
    - dont_deploy/**
